name = "EDA"
uuid = "b2da3285-ee56-486b-95f3-9dc7b9d1c35a"
authors = ["Tuffit"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
CSV = "0.10.15"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
